### ISSUE TITLE
QVariant import erroneously used in typing annotations

### ISSUE THREAD

**Issue by cercata** [PlotPyStack/guidata#65]
I was using guidata with PySide6 with no problems, with the following versions:
PySide==6.4.2
guidata==2.3.0

After updating both to the lastet packages (PySide=6.5.2, guidata==3.0.4), I get an error importing QVariant.

As noted in the QT6 for python doc, QVariant was removed:
https://doc.qt.io/qtforpython-6/considerations.html

In the [guidata](https://pypi.org/project/guidata/) site, I see only PyQt5 is supported.

Is PySide6 planned to be supported on the future ?

**Comment by PierreRaybaut** [comment]
Thanks for the feedback.
The only QVariant import in the code was introduced when adding typing annotations, but it's clearly a mistake: thanks for pointing that out.

In other words, PySide6 is already supported.
