### ISSUE TITLE
Support numpy 2.0

### ISSUE THREAD

**Issue by stkw0** [PlotPyStack/guidata#76]
Currently when using numpy 2.0 the tests will fail with: 

> AttributeError: `np.cast` was removed in the NumPy 2.0 release. Use `np.asarray(arr, dtype=dtype)` instead.

**Comment by PierreRaybaut** [comment]
Thanks for the feedback.

Indeed, there are some changes to be made for full NumPy V2.0 compatibility.

We already have scheduled this for the next few days.
Preliminary actions were done:

- 391baf7b356fd2a0fa8f4639782a58b74a27614c
- 271cf48f4bfac93676840cfffc9ba570ad4aa00c

**Comment by stkw0** [comment]
Thank you for the fast reply, and sorry for the noise. Didn't see the last two commits.

**Comment by PierreRaybaut** [comment]
No worry: in fact, I forgot to create the Issue, so your feedback was the opportunity to do it.

**Comment by PierreRaybaut** [comment]
Done with V3.5.2
